# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            BUILD_PATH: /home/runner/work/java-rdp/java-rdp/target/
          - os: windows-latest
            BUILD_PATH: D:\a\java-rdp\java-rdp\target\

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Get version (Windows)
      uses: pCYSl5EDgo/cat@master
      id: version
      with:
        path: ${{matrix.BUILD_PATH}}version.txt
    - name: Output Version URL File (Linux)
      run: echo -n "${{ steps.version.outputs.text }}" > version_output.txt
      if: matrix.os == 'ubuntu-latest'
    - name: Output Version URL File (Windows)
      run: echo|set /p="${{ steps.version.outputs.text }}" > version_output.txt
      if: matrix.os == 'windows-latest'
    - name: Save Version URL File for other workflows
      uses: actions/upload-artifact@v1
      with:
        name: version_output
        path: version_output.txt
    - name: Get changelog
      uses: pCYSl5EDgo/cat@master
      id: changelog
      with:
        path: ${{matrix.BUILD_PATH}}changelog.txt
    - name: Output Changelog URL File
      run: echo "${{ steps.changelog.outputs.text }}" > changelog_output.txt
    - name: Save Changelog URL File for other workflows
      uses: actions/upload-artifact@v1
      with:
        name: changelog_output
        path: changelog_output.txt
    - name: Zip output (Windows)
      run: cd ${{matrix.BUILD_PATH}} && 7z a -tzip output-${{matrix.os}}.zip lib runtime java-rdp-${{ steps.version.outputs.text }}.exe
      if: matrix.os == 'windows-latest'
    - name: Zip output (Linux)
      run: cd ${{matrix.BUILD_PATH}} && zip -r output-${{matrix.os}}.zip lib runtime java-rdp-${{ steps.version.outputs.text }}.jar
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/upload-artifact@master
      with:
        name: ${{matrix.os}}-artifact
        path: ${{matrix.BUILD_PATH}}
    
    
  create-release:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
    
    - name: Load Version URL File from previous job
      uses: actions/download-artifact@v1
      with:
        name: version_output
    - name: Get version
      uses: pCYSl5EDgo/cat@master
      id: get_version
      with:
        path: version_output/version_output.txt
        
        
        
    - name: Load Changelog URL File from previous job
      uses: actions/download-artifact@v1
      with:
        name: changelog_output
    - name: Get changelog
      uses: pCYSl5EDgo/cat@master
      id: get_changelog
      with:
        path: changelog_output/changelog_output.txt
        
        
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.text }}
        release_name: JRDP – ${{ steps.get_version.outputs.text }}
        body: |
          ${{ steps.get_changelog.outputs.text }}
        draft: false
        prerelease: false
        
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt
        
        
        
  upload-assets:
    needs: create-release
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            BUILD_PATH: /home/runner/work/java-rdp/java-rdp/target/
          - os: windows-latest
            BUILD_PATH: D:\a\java-rdp\java-rdp\target\
    steps:
    
    - uses: actions/download-artifact@master
      with:
        name: ${{matrix.os}}-artifact
        path: ${{matrix.BUILD_PATH}}
    
    
    - name: Load Version URL File from previous job
      uses: actions/download-artifact@v1
      with:
        name: version_output
    - name: Get version
      uses: pCYSl5EDgo/cat@master
      id: get_version
      with:
        path: version_output/version_output.txt
        
    
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v1
      with:
        name: release_url
    - name: Get version
      uses: pCYSl5EDgo/cat@master
      id: get_release_info
      with:
        path: release_url/release_url.txt
        
        
    - name: Upload Release Asset (Windows)
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.text }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{matrix.BUILD_PATH}}output-${{matrix.os}}.zip
        asset_name: jrdp-${{ steps.get_version.outputs.text }}-${{matrix.os}}.zip
        asset_content_type: application/zip
