# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Get version
      uses: pCYSl5EDgo/cat@master
      id: version
      with:
        path: /home/runner/work/java-rdp/java-rdp/target/version.txt
    - name: Get changelog
      uses: pCYSl5EDgo/cat@master
      id: changelog
      with:
        path: /home/runner/work/java-rdp/java-rdp/target/changelog.txt
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: JRDP – ${{ steps.version.outputs.text }}
        body: |
          ${{ steps.changelog.outputs.text }}
        draft: false
        prerelease: false
